In [1]:
from numpy import array
from numpy import diag
from numpy import zeros
from scipy.linalg import svd

from sklearn.preprocessing import LabelEncoder
from sklearn import preprocessing

In [2]:
A = array([
[1,2,3,4,5,6,7,8,9,10],
[11,12,13,14,15,16,17,18,19,20],
[21,22,23,24,25,26,27,28,29,30]])

def missing_values_table(df):    
        mis_val = df.isnull().sum()        
        mis_val_percent = 100 * df.isnull().sum() / len(df)        
        type_column = df.dtypes        
        mis_val_table = pd.concat([mis_val, mis_val_percent, type_column], axis=1)        
        mis_val_table_ren_columns = mis_val_table.rename(columns = {0 : 'Missing Values', 1 : '% of Total Values', 2:'type_column'})
        mis_val_table_ren_columns = mis_val_table_ren_columns[mis_val_table_ren_columns.iloc[:,1] != 0].sort_values('% of Total Values', ascending=False).round(1)
        print ("Your selected dataframe has " + str(df.shape[1]) + " columns.\n"      "There are " + str(mis_val_table_ren_columns.shape[0]) +
              " columns that have missing values.")
        return mis_val_table_ren_columns

    
def scatterplot(x_data, y_data, x_label="", y_label="", title="", color = "r", yscale_log=False):

    # Create the plot object
    _, ax = plt.subplots()

    # Plot the data, set the size (s), color and transparency (alpha)
    # of the points
    ax.scatter(x_data, y_data, s = 10, color = color, alpha = 0.75)

    if yscale_log == True:
        ax.set_yscale('log')

    # Label the axes and provide a title
    ax.set_title(title)
    ax.set_xlabel(x_label)
    ax.set_ylabel(y_label)
    


In [3]:
# Singular value decomposition 
U, s, VT = svd(A)

In [4]:
# create m*n segma 
Sigma = zeros((A.shape[0],A.shape[1]))
# populate Sigma with n x n diagonal matrix
Sigma[:A.shape[0], :A.shape[0]] = diag(s)

In [5]:
# select
n_elements = 2
Sigma = Sigma[:, :n_elements]
VT = VT[:n_elements, :]

# reconstruct
B = U.dot(Sigma.dot(VT))
print(B)
# transform
T = U.dot(Sigma)
print(T)
T = A.dot(VT.T)
print(T)

[[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]
 [11. 12. 13. 14. 15. 16. 17. 18. 19. 20.]
 [21. 22. 23. 24. 25. 26. 27. 28. 29. 30.]]
[[-18.52157747   6.47697214]
 [-49.81310011   1.91182038]
 [-81.10462276  -2.65333138]]
[[-18.52157747   6.47697214]
 [-49.81310011   1.91182038]
 [-81.10462276  -2.65333138]]


In [6]:
from numpy import array
from sklearn.decomposition import TruncatedSVD
# define array
A = array([
[1,2,3,4,5,6,7,8,9,10],
[11,12,13,14,15,16,17,18,19,20],
[21,22,23,24,25,26,27,28,29,30]])
print(A)
# svd
svd = TruncatedSVD(n_components=2)
svd.fit(A)
result = svd.transform(A)
# print(result)

[[ 1  2  3  4  5  6  7  8  9 10]
 [11 12 13 14 15 16 17 18 19 20]
 [21 22 23 24 25 26 27 28 29 30]]


In [7]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import random
from numpy import nan

In [8]:
data = pd.read_csv("testing_19_2020.csv")
df = data.copy()
df = df.drop(['Customer_ID'], axis=1)
df.columns

Index(['Unnamed: 0', 'rev_Mean', 'mou_Mean', 'totmrc_Mean', 'da_Mean',
       'ovrmou_Mean', 'ovrrev_Mean', 'vceovr_Mean', 'datovr_Mean', 'roam_Mean',
       'change_mou', 'change_rev', 'drop_vce_Mean', 'drop_dat_Mean',
       'blck_vce_Mean', 'blck_dat_Mean', 'unan_vce_Mean', 'unan_dat_Mean',
       'plcd_vce_Mean', 'plcd_dat_Mean', 'recv_vce_Mean', 'recv_sms_Mean',
       'comp_vce_Mean', 'comp_dat_Mean', 'custcare_Mean', 'ccrndmou_Mean',
       'cc_mou_Mean', 'inonemin_Mean', 'threeway_Mean', 'mou_cvce_Mean',
       'mou_cdat_Mean', 'mou_rvce_Mean', 'owylis_vce_Mean', 'mouowylisv_Mean',
       'iwylis_vce_Mean', 'mouiwylisv_Mean', 'peak_vce_Mean', 'peak_dat_Mean',
       'mou_peav_Mean', 'mou_pead_Mean', 'opk_vce_Mean', 'opk_dat_Mean',
       'mou_opkv_Mean', 'mou_opkd_Mean', 'drop_blk_Mean', 'attempt_Mean',
       'complete_Mean', 'callfwdv_Mean', 'callwait_Mean', 'churn', 'months',
       'uniqsubs', 'actvsubs', 'new_cell', 'crclscod', 'asl_flag', 'totcalls',
       'totmou', 'tot

In [9]:
df = df.loc[:, ~df.columns.str.contains('^Unnamed')]
df = df.dropna()
missing_values_table(df)

Your selected dataframe has 99 columns.
There are 0 columns that have missing values.


Empty DataFrame
Columns: [Missing Values, % of Total Values, type_column]
Index: []

In [10]:
df.columns[df.dtypes.values == 'object']

Index(['new_cell', 'crclscod', 'asl_flag', 'prizm_social_one', 'area',
       'dualband', 'refurb_new', 'hnd_webcap', 'ownrent', 'dwlltype',
       'marital', 'infobase', 'HHstatin', 'dwllsize', 'ethnic', 'kid0_2',
       'kid3_5', 'kid6_10', 'kid11_15', 'kid16_17', 'creditcd'],
      dtype='object')

In [11]:
category_ = ['new_cell', 'crclscod', 'asl_flag', 'prizm_social_one', 'area',
       'dualband', 'refurb_new', 'hnd_webcap', 'ownrent', 'dwlltype',
       'marital', 'infobase', 'HHstatin', 'dwllsize', 'ethnic', 'kid0_2',
       'kid3_5', 'kid6_10', 'kid11_15', 'kid16_17', 'creditcd']
len(category_)

21

In [12]:
df_encoded = df.copy()

In [13]:
df_encoded

rev_Mean    mou_Mean  totmrc_Mean   da_Mean  ovrmou_Mean  ovrrev_Mean  \
0      23.997500  219.250000    22.500000  0.247500     0.000000      0.00000   
1      57.492500  482.750000    37.425000  0.247500    22.750000      9.10000   
2      16.990000   10.250000    16.990000  0.000000     0.000000      0.00000   
3      38.000000    7.500000    38.000000  0.000000     0.000000      0.00000   
4      55.230000  570.500000    71.980000  0.000000     0.000000      0.00000   
...          ...         ...          ...       ...          ...          ...   
99995  58.719985  513.559937    46.179136  0.888828    41.072247     13.55956   
99996  58.719985  513.559937    46.179136  0.888828    41.072247     13.55956   
99997  58.719985  513.559937    46.179136  0.888828    41.072247     13.55956   
99998  58.719985  513.559937    46.179136  0.888828    41.072247     13.55956   
99999  58.719985  513.559937    46.179136  0.888828    41.072247     13.55956   

       vceovr_Mean  datovr_Mean  roam_Mean  change_mou  ...  dwllsize  \
0         0.000000     0.000000   0.000000 -157.250000  ...         A   
1         9.100000     0.000000   0.000000  532.250000  ...         A   
2         0.000000     0.000000   0.000000   -4.250000  ...         A   
3         0.000000     0.000000   0.000000   -1.500000  ...         D   
4         0.000000     0.000000   0.000000   38.500000  ...         O   
...            ...          ...        ...         ...  ...       ...   
99995    13.295062     0.261318   1.286405  -13.933818  ...         A   
99996    13.295062     0.261318   1.286405  -13.933818  ...         A   
99997    13.295062     0.261318   1.286405  -13.933818  ...         A   
99998    13.295062     0.261318   1.286405  -13.933818  ...         A   
99999    13.295062     0.261318   1.286405  -13.933818  ...         A   

       forgntvl  ethnic  kid0_2  kid3_5  kid6_10  kid11_15  kid16_17  \
0           0.0       N       U       U        U         U         U   
1           0.0       Z       U       U        U         U         U   
2           0.0       N       U       Y        U         U         U   
3           0.0       U       Y       U        U         U         U   
4           0.0       I       U       U        U         U         U   
...         ...     ...     ...     ...      ...       ...       ...   
99995       0.0       S       U       U        U         Y         U   
99996       0.0       N       U       U        Y         Y         Y   
99997       0.0       U       Y       Y        U         U         U   
99998       0.0       S       U       U        U         U         U   
99999       0.0       H       U       U        U         U         U   

       creditcd  eqpdays  
0             Y    361.0  
1             Y    240.0  
2             Y   1504.0  
3             Y   1812.0  
4             Y    434.0  
...         ...      ...  
99995         Y    773.0  
99996         Y    835.0  
99997         N    433.0  
99998         N     75.0  
99999         N      5.0  

[99951 rows x 99 columns]

In [14]:
cat_bool  = [ 'kid0_2','kid3_5', 'kid6_10', 'kid11_15', 'kid16_17']
# df_encoded['kid0_2'] = df_encoded['kid0_2'].map({'U':0 , 'Y':1})
# print(df_encoded['kid0_2'])
for value in cat_bool: 
    df_encoded[value] = df_encoded[value].map({'U':0 , 'Y':1})
    

In [15]:
category_ = [x for x in category_ if x not in cat_bool]
df_encoded['creditcd'] = df_encoded['creditcd'].map({'N':0 , 'Y':1})
len(category_)
print(category_)


['new_cell', 'crclscod', 'asl_flag', 'prizm_social_one', 'area', 'dualband', 'refurb_new', 'hnd_webcap', 'ownrent', 'dwlltype', 'marital', 'infobase', 'HHstatin', 'dwllsize', 'ethnic', 'creditcd']


In [16]:
category_ = [ x for x in category_ if x not in 'creditcd' ]
len(category_)

15

In [17]:
category_

['new_cell',
 'crclscod',
 'asl_flag',
 'prizm_social_one',
 'area',
 'dualband',
 'refurb_new',
 'hnd_webcap',
 'ownrent',
 'dwlltype',
 'marital',
 'infobase',
 'HHstatin',
 'dwllsize',
 'ethnic']

In [18]:
cat_1 = ['dwlltype', 'ownrent', 'infobase', 'refurb_new']
df_encoded['dwlltype'] = df_encoded['dwlltype'].map({'S':0 , 'M':1})
df_encoded['ownrent'] = df_encoded['ownrent'].map({'R':0 , 'O':1})
df_encoded['infobase'] = df_encoded['infobase'].map({'M':0 , 'N':1})
df_encoded['refurb_new'] = df_encoded['refurb_new'].map({'R':0 , 'N':1})

category_ = [x for x in category_ if x not in cat_1 ]
missing_values_table(df_encoded)

Your selected dataframe has 99 columns.
There are 0 columns that have missing values.


Empty DataFrame
Columns: [Missing Values, % of Total Values, type_column]
Index: []

In [19]:
print(category_)

['new_cell', 'crclscod', 'asl_flag', 'prizm_social_one', 'area', 'dualband', 'hnd_webcap', 'marital', 'HHstatin', 'dwllsize', 'ethnic']


In [20]:
df_encoded['asl_flag'] = df_encoded['asl_flag'].map({'N':0 , 'Y':1})
category_ = [ x for x in category_ if x not in 'asl_flag' ]

for i in category_:
    feature = df_encoded[i].value_counts()
    print(feature.index)

Index(['U', 'Y', 'N'], dtype='object')
Index(['AA', 'A', 'BA', 'CA', 'EA', 'B', 'DA', 'ZA', 'C', 'A2', 'E4', 'U', 'E',
       'D4', 'GA', 'Z4', 'D', 'I', 'G', 'JF', 'Z', 'CY', 'J', 'C2', 'M', 'ZY',
       'D5', 'B2', 'K', 'W', 'C5', 'V1', 'U1', 'EM', 'Z5', 'Y', 'EC', 'GY',
       'O', 'CC', 'E2', 'IF', 'Z1', 'H', 'P1', 'L', 'D2', 'Z2', 'TP', 'EF',
       'A3', 'S', 'V', 'ZF'],
      dtype='object')
Index(['S', 'U', 'C', 'T', 'R'], dtype='object')
Index(['NEW YORK CITY AREA', 'LOS ANGELES AREA', 'DC/MARYLAND/VIRGINIA AREA',
       'MIDWEST AREA', 'SOUTHWEST AREA', 'ATLANTIC SOUTH AREA',
       'CALIFORNIA NORTH AREA', 'NEW ENGLAND AREA', 'DALLAS AREA',
       'CHICAGO AREA', 'GREAT LAKES AREA', 'OHIO AREA', 'NORTH FLORIDA AREA',
       'HOUSTON AREA', 'NORTHWEST/ROCKY MOUNTAIN AREA',
       'CENTRAL/SOUTH TEXAS AREA', 'SOUTH FLORIDA AREA', 'TENNESSEE AREA',
       'PHILADELPHIA AREA'],
      dtype='object')
Index(['Y', 'N', 'T', 'U'], dtype='object')
Index(['WCMB', 'WC', 'UNKW'], dtype=

In [21]:
cat_2 = category_.copy()
for val in category_:
    name = df_encoded.groupby(val).size()/len(df_encoded)
    df_encoded.loc[:, val+'_encoded'] =  df_encoded[val].map(name)
    df_encoded = df_encoded.drop([val],axis=1)


In [22]:
for val in category_:
    print(df_encoded[val+'_encoded'])

0        0.669158
1        0.137848
2        0.192995
3        0.192995
4        0.192995
           ...   
99995    0.669158
99996    0.669158
99997    0.669158
99998    0.669158
99999    0.669158
Name: new_cell_encoded, Length: 99951, dtype: float64
0        0.169963
1        0.064201
2        0.014557
3        0.041070
4        0.169963
           ...   
99995    0.041070
99996    0.001891
99997    0.036698
99998    0.064201
99999    0.041070
Name: crclscod_encoded, Length: 99951, dtype: float64
0        0.347090
1        0.254825
2        0.347090
3        0.161869
4        0.254825
           ...   
99995    0.254825
99996    0.347090
99997    0.254825
99998    0.254825
99999    0.347090
Name: prizm_social_one_encoded, Length: 99951, dtype: float64
0        0.043291
1        0.051425
2        0.046523
3        0.051425
4        0.054537
           ...   
99995    0.066343
99996    0.066343
99997    0.061880
99998    0.061880
99999    0.066343
Name: area_encoded, Length: 99951, dty

In [23]:
df_encoded

rev_Mean    mou_Mean  totmrc_Mean   da_Mean  ovrmou_Mean  ovrrev_Mean  \
0      23.997500  219.250000    22.500000  0.247500     0.000000      0.00000   
1      57.492500  482.750000    37.425000  0.247500    22.750000      9.10000   
2      16.990000   10.250000    16.990000  0.000000     0.000000      0.00000   
3      38.000000    7.500000    38.000000  0.000000     0.000000      0.00000   
4      55.230000  570.500000    71.980000  0.000000     0.000000      0.00000   
...          ...         ...          ...       ...          ...          ...   
99995  58.719985  513.559937    46.179136  0.888828    41.072247     13.55956   
99996  58.719985  513.559937    46.179136  0.888828    41.072247     13.55956   
99997  58.719985  513.559937    46.179136  0.888828    41.072247     13.55956   
99998  58.719985  513.559937    46.179136  0.888828    41.072247     13.55956   
99999  58.719985  513.559937    46.179136  0.888828    41.072247     13.55956   

       vceovr_Mean  datovr_Mean  roam_Mean  change_mou  ...  new_cell_encoded  \
0         0.000000     0.000000   0.000000 -157.250000  ...          0.669158   
1         9.100000     0.000000   0.000000  532.250000  ...          0.137848   
2         0.000000     0.000000   0.000000   -4.250000  ...          0.192995   
3         0.000000     0.000000   0.000000   -1.500000  ...          0.192995   
4         0.000000     0.000000   0.000000   38.500000  ...          0.192995   
...            ...          ...        ...         ...  ...               ...   
99995    13.295062     0.261318   1.286405  -13.933818  ...          0.669158   
99996    13.295062     0.261318   1.286405  -13.933818  ...          0.669158   
99997    13.295062     0.261318   1.286405  -13.933818  ...          0.669158   
99998    13.295062     0.261318   1.286405  -13.933818  ...          0.669158   
99999    13.295062     0.261318   1.286405  -13.933818  ...          0.669158   

       crclscod_encoded  prizm_social_one_encoded  area_encoded  \
0              0.169963                  0.347090      0.043291   
1              0.064201                  0.254825      0.051425   
2              0.014557                  0.347090      0.046523   
3              0.041070                  0.161869      0.051425   
4              0.169963                  0.254825      0.054537   
...                 ...                       ...           ...   
99995          0.041070                  0.254825      0.066343   
99996          0.001891                  0.347090      0.066343   
99997          0.036698                  0.254825      0.061880   
99998          0.064201                  0.254825      0.061880   
99999          0.041070                  0.347090      0.066343   

       dualband_encoded  hnd_webcap_encoded  marital_encoded  \
0              0.722724            0.843803         0.179418   
1              0.231904            0.153845         0.179418   
2              0.231904            0.153845         0.316145   
3              0.231904            0.153845         0.316145   
4              0.722724            0.843803         0.179418   
...                 ...                 ...              ...   
99995          0.231904            0.153845         0.316145   
99996          0.231904            0.153845         0.316145   
99997          0.722724            0.843803         0.072395   
99998          0.722724            0.843803         0.379756   
99999          0.722724            0.843803         0.052286   

       HHstatin_encoded  dwllsize_encoded  ethnic_encoded  
0              0.630189          0.767026        0.339827  
1              0.630189          0.767026        0.045132  
2              0.630189          0.767026        0.339827  
3              0.630189          0.011296        0.111345  
4              0.630189          0.019369        0.038799  
...                 ...               ...             ...  
99995          0.630189          0.767026        0.129764  
99996   

In [24]:
# Normalize total_bedrooms column


In [25]:
cat_3 = ['new_cell_encoded', 'crclscod_encoded', 'prizm_social_one_encoded', 'area_encoded', 'dualband_encoded', 'hnd_webcap_encoded', 'marital_encoded', 'HHstatin_encoded', 'dwllsize_encoded', 'ethnic_encoded']
    
columns = df_encoded.columns
to_normalize_ = [ x for x in columns if x  not in cat_3 ]
df_scaled = df_encoded.copy()
df_scaled.columns

Index(['rev_Mean', 'mou_Mean', 'totmrc_Mean', 'da_Mean', 'ovrmou_Mean',
       'ovrrev_Mean', 'vceovr_Mean', 'datovr_Mean', 'roam_Mean', 'change_mou',
       'change_rev', 'drop_vce_Mean', 'drop_dat_Mean', 'blck_vce_Mean',
       'blck_dat_Mean', 'unan_vce_Mean', 'unan_dat_Mean', 'plcd_vce_Mean',
       'plcd_dat_Mean', 'recv_vce_Mean', 'recv_sms_Mean', 'comp_vce_Mean',
       'comp_dat_Mean', 'custcare_Mean', 'ccrndmou_Mean', 'cc_mou_Mean',
       'inonemin_Mean', 'threeway_Mean', 'mou_cvce_Mean', 'mou_cdat_Mean',
       'mou_rvce_Mean', 'owylis_vce_Mean', 'mouowylisv_Mean',
       'iwylis_vce_Mean', 'mouiwylisv_Mean', 'peak_vce_Mean', 'peak_dat_Mean',
       'mou_peav_Mean', 'mou_pead_Mean', 'opk_vce_Mean', 'opk_dat_Mean',
       'mou_opkv_Mean', 'mou_opkd_Mean', 'drop_blk_Mean', 'attempt_Mean',
       'complete_Mean', 'callfwdv_Mean', 'callwait_Mean', 'churn', 'months',
       'uniqsubs', 'actvsubs', 'asl_flag', 'totcalls', 'totmou', 'totrev',
       'adjrev', 'adjmou', 'adjqty', 'a

In [26]:

res = pd.DataFrame( )
for i in to_normalize_:
    x_array = np.array(df_scaled[i])
    normalized_X = preprocessing.normalize([x_array])
    #print(normalized_X)
    normalized_X = np.reshape(normalized_X, (99951,1))
    #normalized_X = normalized_X.tolist()   
    #print(normalized_X)
    data = []
    for value in normalized_X:
        data.append(value)
        
    # test_ = pd.DataFrame(data, columns= [i])
    test_ = pd.DataFrame(data, columns= [i+'_scaled'])
    # print(test_)
    res = pd.concat([res,test_], axis=1)
    
    # df_ = df_.append(test_)
    # df_scaled = pd.concat(test_, ignore_index=True)
    
    # print(df_scaled)
    # scaled_feature()
    # df_scaled = pd.DataFrame( i: normalized_X )
    # x = df_encoded.values #returns a numpy array
    # min_max_scaler = preprocessing.MinMaxScaler()
    # x_scaled = min_max_scaler.fit_transform(x)
    # df = pd.DataFrame(x_scaled)
    
    #df_encoded.loc[:, i+'_normalized'] =  normalized_X
    #df_encoded = df_encoded.drop([i],axis=1)
 

In [28]:
#df_s
df_scaled.columns
res.columns

Index(['rev_Mean_scaled', 'mou_Mean_scaled', 'totmrc_Mean_scaled',
       'da_Mean_scaled', 'ovrmou_Mean_scaled', 'ovrrev_Mean_scaled',
       'vceovr_Mean_scaled', 'datovr_Mean_scaled', 'roam_Mean_scaled',
       'change_mou_scaled', 'change_rev_scaled', 'drop_vce_Mean_scaled',
       'drop_dat_Mean_scaled', 'blck_vce_Mean_scaled', 'blck_dat_Mean_scaled',
       'unan_vce_Mean_scaled', 'unan_dat_Mean_scaled', 'plcd_vce_Mean_scaled',
       'plcd_dat_Mean_scaled', 'recv_vce_Mean_scaled', 'recv_sms_Mean_scaled',
       'comp_vce_Mean_scaled', 'comp_dat_Mean_scaled', 'custcare_Mean_scaled',
       'ccrndmou_Mean_scaled', 'cc_mou_Mean_scaled', 'inonemin_Mean_scaled',
       'threeway_Mean_scaled', 'mou_cvce_Mean_scaled', 'mou_cdat_Mean_scaled',
       'mou_rvce_Mean_scaled', 'owylis_vce_Mean_scaled',
       'mouowylisv_Mean_scaled', 'iwylis_vce_Mean_scaled',
       'mouiwylisv_Mean_scaled', 'peak_vce_Mean_scaled',
       'peak_dat_Mean_scaled', 'mou_peav_Mean_scaled', 'mou_pead_Mean_scale

In [29]:
svd = TruncatedSVD(n_components=35)
svd.fit(res)
result = svd.transform(res)